# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sonja Secret Sauce
tagline:             'And other thoughts'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              olsonso
  url:               https://twitter.com/olsonso
  email:             olsno1sonja@gmail.com

# Custom vars
version:             1.0.0
